.TH DCAL 1 dcal\-VERSION
.SH NAME
dcal \- dynamic calendar
.SH SYNOPSIS
.B dcal
.RB [ \-b]
.RB [ \-l]
.RB [ \-k]
.RB [ \-fn
.IR font ]
.RB [ \-bg
.IR color ]
.RB [ \-bd
.IR color ]
.RB [ \-cf
.IR color ]
.RB [ \-of
.IR color ]
.RB [ \-tf
.IR color ]
.RB [ \-hf
.IR color ]
.RB [ \-x
.IR offset ]
.RB [ \-y
.IR offset ]
.RB [ dates ]
.sp
.B dcal -h
.sp
.B dcal -v
.SH DESCRIPTION
.B dcal
is a dynamic calendar for X.  It shows the current month and allows you to
navigate to other months.
.SH OPTIONS
.TP
.BI \-b
draws the calendar on the bottom of the screen.
.TP
.BI \-l
draws the calendar on the left of the screen.
.TP
.BI \-k
do not grab the keyboard nor use it for input.
.TP
.BI \-fn " font"
defines the font or font set used.
.TP
.BI \-bg " color"
defines the background color.
.IR #RGB ,
.IR #RRGGBB ,
and X color names are supported.
.TP
.BI \-bd " color"
defines the border color.
.TP
.BI \-cf " color"
defines the current month foreground color.
.TP
.BI \-of " color"
defines the other month foreground color.
.TP
.BI \-cf " color"
defines the forgeround color for today.
.TP
.BI \-hf " color"
defines the foreground color for hilights.
.TP
.BI \-x " offset"
defines an offset in the horizontal direction to adjust where the calendar is
shown.
.TP
.BI \-y " offset"
defines an offset in the vertical direction to adjust where the calendar is
shown.
.TP
.B \-h
prints usage information to stdout, then exits.
.TP
.B \-v
prints version information to stdout, then exits.
.SH IMPORTANT DATES
Any other arguments are taken to be important dates that will be drawn with the
hilight color.  The dates should be formatted as YYYYMMDD without any
separators.  Only 32 dates are supported, any more will be ignored.
.SH USAGE
dcal can be controlled via the mouse or the keyboard.  The following commands
are recognized:
.TP
.B Space
Jump back to the current date.
.TP
.B H, Left
Go back one day.
.TP
.B L, Right
Go forward one day.
.TP
.B K, Up
Go back one week.
.TP
.B J, Down
Go forward one week.
.TP
.B Shift\-K, Mouse wheel up
Go back one month.
.TP
.B Shift\-J, Mouse wheel down
Go forward one month.
.TP
.B Escape, Q, Right click
Exit dcal.
.SH SEE ALSO
.IR dwm (1),
.IR dmenu (1)
